### ISSUE TITLE
`get_summary_from_phoenix` for both Pronet and Prescient network?

### ISSUE THREAD

**Issue by kcho** [AMP-SCZ/utility#6]
Are we using `get_summary_from_phoenix` function for both Pronet and Prescient network directories? Below are a list of  differences in Prescient folder structure from Pronet, which may require a number of additional logics to the function, if we are using the same function. The differences mainly arise from differences in the type of data source used, eg. `RPMS` vs `REDCap` & `XNAT` vs `mediaflux`.

- [x] 1. MRI data: Prescient will have a `.zip` file under `mri` directory.
- [x] 2. Survey data: RPMS exports a `.csv` file for each type of measure under `surveys` directory.
- [ ] 3. Scan sheets or Run sheets: Most of the Run sheets are not being exported yet by RPMS export due to the delay in the overall project.
- [x] 4. There are `Pronet` strings in a few part of the logics, which may have to be tweaked.

**Comment by tashrifbillah** [comment]
> Are we using get_summary_from_phoenix function for both Pronet and Prescient network directories?

Yes

---

I see what you mean. There are a number of `Pronet` strings in the glob patterns:

https://github.com/AMP-SCZ/utility/blob/aa905c38b5fe9dc753c60f65690e309651e93034/subject_files_status_for_dpdash.py#L48-L57

Since you have a better idea about downloaded files, it is better if you write us a` get_summary_from_phoenix` function for `PRESCIENT` network.

**Comment by tashrifbillah** [comment]
Too old, closing for tracking active issues better.
